- configure.ac
- gmond/python_modules/Makefile.am
- gmond/python_modules/cpu/Makefile.am
At some point the default set of `pyconf` files and which modules were
actually being built got out of sync.  This meant the cpu python files
were not present but were referenced in a `pyconf` file, resulting in
`Unable to find the metric information for foo` errors when gmond was
started. (And obviously there were no metrics either.)
fix #180
> build cpu_stat along with the other python modules

- ganglia.spec.in
Hi,
I have found that I needed to have e2fsprogs-devel installed for ganglia to build on RHEL5 or in an EPEL5 mock environment.
The attached patch adds this as a BuildRequires.
Cheers,
RobbieAB.
> Adding e2fsprogs-devel to the BuildRequires for RHEL5.

- INSTALL
- configure.ac
- gmetad/Makefile.am
- lib/Makefile.am
- lib/hash.c
- lib/hash.h
There is some concern around cutting a 3.7 release with the CK dependency and its (lack of) packaging in major distributions. Additionally, people with large numbers of data sources experience CPU spikes when aggregating even a small number of metrics. This latter point is solvable with a new hash table implementation, but that is a task for a different release.
This changeset removes CK rwlocks and replaces them with APR rwlocks. This should solve the CPU spiking, and since APR was already a dependence, solve the packaging concerns as well.
> Switch from CK rwlocks to APR rwlocks

- gmond/python_modules/apache_status/apache_status.py
`_Worker_Thread` was removed in:
* 5eb4434d4bf4eb9d4ef83085dc445ef42249f152
* ganglia/gmond_python_modules@b1a20da853cc4b8d9acfc787d6f3635a1a3a3f68
fix ganglia/gmond_python_modules#176
> remove stray reference to old variable

- BUGS
- mans/gmetad.1
- mans/gmetric.1
- mans/gmond.1
- mans/gstat.1
NOTE: These files have a 'DO NOT MODIFY THIS FILE' header, but they
appear to have been edited multiple times.  Notable runing `help2man`
today does not produce any `REPORTING BUGS` section.  There is
probably a more modern way to generate man pages that should be
considered in the future.
ML Ref: https://www.mail-archive.com/ganglia-developers%40lists.sourceforge.net/msg06496.html
> update old bugzilla bug report links to github

- gmond/python_modules/memory/mem_stats.py
`/proc/meminfo` does not provide a 'SwapUsed', instead relying on
the user to do the simple subtraction.  This isn't hard, but
monitoring & graphing tools that use ganglia metrics often do
not have a mechanism to do compound operations.
> report `mem_swap_used`

- gmond/python_modules/process/procstat.py
there is a race between listing all the /proc/pid dirs and reading the
stat files in those dirs. try/except'ing each stat file individually
fixes this race.
there remains the corner case where the pid we are searching for is
one of those that has exited. this is detected and [] is returned.
this function's previous fall-through of returning None in case of any
problems was not understood by callers. this caused many errors in
abrt/syslog of the form
[PYTHON] Can't call the metric handler function for [procstat_*_cpu] in the python module [procstat].
see eg.
https://github.com/ganglia/gmond_python_modules/issues/114
by always returning [] in the worst case we solve that problem.
> skip reading the stat files of processes that have exited.

- gmond/python_modules/apache_status/apache_status.py
91649c93d05cd6722033ae829d4cf18ec60b9ec2 introduced a regression when
cleaning up inconsistencies in whitespace.  An `else` block become
aligned with `for` instead of `if`.  This is unusual, but sadly
syntactically correct code.  This would cause some metrics, including
`ap_rps`, and `ap_busy_workers` to always report zeros.
> fix apache_status.py whitespace regressing

- gmond/python_modules/process/procstat.py
This is to fix https://github.com/ganglia/gmond_python_modules/issues/156
This changes get_stat(name) to use split() to determine the process name and the label, rather than searching for the position of underscores.
> Handle process names containing 1 or more underscores

- libmetrics/linux/metrics.c
The calculation was failing on large volumes (>10Tb), this fix corrects it
> updated metrics.c disk usage to use double instead of float

- gmond/gmond.c
As requested by @cburroughs, I've split pull request #168 into two.
This one contains the changes to gmond hashtable locking.  I've been running this change in production since last October with no ill effects.
> Acquire lock before accessing hash tables.

- gmond/gmond.c
Memory leaks when using `override_hostname`, this should fix it.
> Fix memory leak 

- gmond/python_modules/apache_status/apache_status.py
https://github.com/apache/httpd/commit/f89436eac5ff5874efabeba01c3e75a90839b73a#diff-a25f910604a349cd1173529f96b0571eR431 adds the hostname as the first line on the mod_status output. This breaks ganglia at the moment as it's expecting each line to have a ": " separating key and values.
> Ignore hostname line in Apache 2.4.16

- libmetrics/openbsd/metrics.c
Some header changes happened somewhere and now this has to be specified manually.
> can't build on OpenBSD 5.7 without this

- gmond/python_modules/network/netstats.py
If a metric group shows up in the network file sometime after initial
module startup, a KeyError may occur in get_metrics.  This causes the
netstats module to be non-functional until gmond is restarted.
Particularly, the IcmpMsg group will not be present until the first
IcmpMsg has been processed.
NOTE: I found this by dragging gmond through gdb.  It seems that the python exceptions / tracebacks aren't logged.  :(
> Avoid KeyError for new metric groups.

- gmond/python_modules/network/netstats.py
Since indent of `netstats.py` is a mix of tab and whitespace, unify this into whitespace.
In addition, slightly fix format.
> fix indent to use whitespace

- .gitignore
This adds a few transient files to the git ignore list--should clean up the "git status" output when actively developing things.
> Ignore files:  tags, *.m4, *.swp

- libmetrics/linux/metrics.c
ZFS mounts don't start with '/dev/', so look out for that when skipping mount entries.
> support fs size for ZFS on Linux

- gmond/g25_config.c
- lib/default_conf.h.in
Simple patch to remove a trailing space in default_conf.h.in.
> Remove trailing space in default gmond.conf header file

- gmetad/gmetad.c
Fix race condition where new metrics are added while old metric still gets send
to carbon server. The carbon log is reporting invalid metrics.
This minor change does solve the issue.
> Fix race condition - invalid metric send to carbon server

- gmond/gmond.c
Segfault when gmond fails to open socket,
this happens when fd reaches ulimit.
Signed-off-by: Hiroshi Miura <miurahr@linux.com>
Signed-off-by: Takashi Kajinami <kajinamit@nttdata.co.jp>
> Fix null closing when gmond fails to open socket.

- gmond/sflow_gmetric.h
Apparently host sflow had used the longer name (`guest_nice`) for the additional CPU metric,
but make it use the shorter name (`gnice`) so that it fits with the rest of gmond/gmetad/ganglia-web.
> Make sflow use the short guest nice name too

- libmetrics/linux/metrics.c
Ganglia needs to know about ARM 64 CPUs.  This patch adds recognition for that platform.
> Add aarch64 support

- gmond/python_modules/process/procstat.py
> Report mem as float, to avoid uint32 overflow

- gmond/gmond.c
The 2x SO_RCVBUF behavior is specific to Linux.  When requesting the
size of a buffer an OS might reasonably say it's exactly the size you
just asked for.  This is the behavior on Illumos and FreeBSD.
To avoid a thicket of environment specific conditionals while
accommodating Linux, downgrade to a log warning instead of
EXIT_FAILURE.
NOTE: Removed the now misleading APR 0.9.4 warning.  That version was
released in 2003.
> downgrade udp recv buffer length check

- gmetad/gmetad.c
- gmetad/process_xml.c
RE: c8ca8bc68fae775d588aeef8e35db3f9255b48c3
The assumption that the sflow vm metric will always be of the form
name.vcpu_num is incorrect for environments where the virt name is the
fqdn.
> The way forward is sometimes the way back

- gmond/modules/cpu/mod_multicpu.c
Due to a copy/paste error in a3833fa42cc8b5bca75d8c1e78baec643cfadf53,
the wrong values (user cpu) were being used for steal cpu comparisons.
> Fix wrong steal values being reported for multi_cpu

- gmetad-python/gmetad-python.service.in
- gmetad/gmetad.service.in
- gmond/gmond.service.in
Having only network waits for the interfaces to be present.
Specifying network-online means to wait until the interfaces are configured, in the case of dhcp, wait until a lease is given and network is up before bringing this service online.
https://baptiste-wicht.com/posts/2014/10/linux-tip-force-systemd-networkd-to-wait-for-dhcp.html
> issue 266, requiring dhcp and network interfaces to be UP

- libmetrics/linux/metrics.c
32-bit linux systems often use 32-bit values for network byte/packet counters, but we've been assuming 64-bit rollover if the system supports strtoull.  Per d17a120fe4a9905122ab521c5608d752e57246b6 (see #83), this was because some 32-bit systems use 64-bit network byte/packet counters, so it's not sufficient to check system type.  Instead, just see if the previous value looks like a 32-bit or 64-bit value - if someone's going from a value that fits in 32 bits to one that's overflowed 64 in between checks, a) that's absurd bandwidth, and b) it's no longer a reasonable assumption that they only rolled over *once* either.
This fixes #140.
> fix net byte/packet stats on 32-bit linux

- lib/hash.c
* Fix gmetad segmentation fault
* Relates to #293
* I think this commit removed hash key check, so hash_delete() always removes first bucket
* https://github.com/ganglia/monitor-core/commit/02524bf2f5485cfd4cddb66bd3280e5a08a2232c#diff-b06f83698bd50e05e13870bc05676cc0L369
* https://gist.github.com/junichi-tanaka/554f6b94c8ef722e11931f596c675a7f#file-test-c
```
$ ./test
172.16.1.56
```
```
$ ./test
172.16.1.1
```
* https://gist.github.com/junichi-tanaka/19a14cb1d3b1820d61dbecae82ff9040
> Fix issue 293

- ganglia.pod
- gmetad/server.c
- gmond/modules/memory/mod_mem.c
- lib/default_conf.h.in
- lib/libgmond.c
- libmetrics/libmetrics.h
- libmetrics/linux/metrics.c
According to later versions of procps, the top(1) value for "buff/cache"
memory is supposed in addition to Buffers/Cached to also include Slab.
Interestingly, the biggest impact of this is in the "used" memory shown
since that value is not reported but just calculated using the others:
``` C
// {"Cached",       &kb_page_cache},
kb_main_cached = kb_page_cache + kb_slab;
kb_swap_used = kb_swap_total - kb_swap_free;
kb_main_used = kb_main_total - kb_main_free - kb_main_cached - kb_main_buffers;
```
In order to have more accurate memory reporting on Linux, make sure to
include this metric in the default configuration for the memory module.
>  Add Slab memory to linux-specific memory metrics

- libmetrics/linux/metrics.c
If arch is not know, gstat breaks on all node of a cluster. So having unknown fixes this.
> - added unknown arch as default in arch detection

- gmetad/server.c
- lib/default_conf.h.in
Previously we would export Slab, but it should have been SReclaimable.
This is because we normally use the metric to estimate the memory Use.
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=565518
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=799716
> Use only the reclaimable Slab memory by default

- ganglia.pod
- gmetad/server.c
- gmond/modules/memory/mod_mem.c
- lib/default_conf.h.in
- libmetrics/libmetrics.h
- libmetrics/linux/metrics.c
Recent versions of Linux gave up on trying to explain the various
types of memory, and added an explicit "MemAvailable" proc field.
Where available ;-), report this value since it can make the memory
graph even better - somewhat similar to load_one and proc_run...
> Also add mem_available, to further improve stats

- gmetad/gmetad.c
The write_root_summary function calls write_data_to_rrd, passing in
metric->slope for the slope parameter. However, metric->slope is a
string offset into the strings buffer and not a valid ganglia_slope_t
value. This results in an incorrectly constructed RRD, and many
warning messages emitted for every subsequent update.
The fix is to use cstr_to_slope() to translate the slope string into
a proper ganglia_slope_t value.
> Pass in correct slope enumeration value constructing root summary RRD.

- gmond/gmond.c
- lib/libgmond.c
**Symptom**:  gmond emits the following error message when configured with host spoofing
```
Incorrect format for spoof argument. exiting.
```
**Mitigation**: allocation of spoofed host id on cached metadata objects must be from the global pool and NOT a temporary pool.
**Secondary fixes**:
1. Guard against zero-length host ids in Ganglia_host_get()
2. Initialize global "myhost" character array to empty string to match expected pre-condition throughout libgmond.c
> Mitigation of "Incorrect format for spoof argument. exiting." errors

- libmetrics/darwin/metrics.c
There is a small typo in libmetrics/darwin/metrics.c.
Should read `statistics` rather than `statstics`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, statstics -> statistics
